### ISSUE TITLE
请问代理时，不能用本地文件代理吗？

### ISSUE THREAD

**Issue by kaven85** [goddyZhao/nproxy#42]
代理时，我是配置的本地相对路径的文件。
代理配置文件和要代理的文件放到同一目录下。配置文件中就直接配置文件名了，但代理时报错说不是一个可用的路径

**Comment by goddyZhao** [comment]
你好，多谢提问。请使用绝对路径，另外如果你是windows的话注意路径分隔符要使用\\

**Comment by kaven85** [comment]
谢谢。
如果支持以配置文件的路径查找就好了。
