### ISSUE TITLE
在Mac下好使吗？

### ISSUE THREAD

**Issue by xiaoqiang-zhao** [goddyZhao/nproxy#48]
我配置了http代理，其他网站就访问不了了，所以我想这个代理应该生效了；

我安装了nproxy，运行nproxy -V可以拿到版本号1.4.5，所以我猜nproxy的安装应该没有问题；

我运行 nproxy -l code/cellar/web/articles/nproxy/config.js，nproxy也启动了，我的config文件内容是这样：

```
module.exports = [
    {
        pattern: 'a.js',
        responder:  "/Users/zhaoxiaoqiang/code/cellar/web/b.js"
    }
];
```

然后我再本地启动了一个网站，访问a.js，发现无法访问，关闭代理可以访问，谁能告诉我这是怎么回事？哪里错了吗？（代理的被动模式开和不开一个样）

**Comment by goddyZhao** [comment]
NProxy是支持Mac的

理论上就算设置了nproxy代理，只要你网络环境是ok的，都可以访问的。

你看看你无法访问的时候nproxy有什么错误输出吗？

**Comment by xiaoqiang-zhao** [comment]
没有输出错误，一切都很安静，可以加个Q吗，指导一下，看看是哪里用的不对，我的Q 183846176

**Comment by goddyZhao** [comment]
感觉你代理没设置对，把你设置代理的浏览器截图贴出来看看吧

**Comment by goddyZhao** [comment]
先关闭了，有问题再reopen
